### ISSUE TITLE
Admin user create process does not allow specifying a password.

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/api#117]
In order to ease the setup and configuration process the rake etcd process should allow the end user to specify a password. The current passwords do not have sufficient complexity of length and or character types so we need a way to drive this input from the user side rather than forcing the user to accept a random password.

**Comment by mkudlej** [comment]
@japplewhite  You can change password after installation to more secure. Also there can be implementation for testing password strength.

**Comment by pmjunior** [comment]
How can I change admin password?

**Comment by fbalak** [comment]
>The current passwords do not have sufficient complexity of length and or character types

I agree, the password is currently generated from [8 hexadecimal characters](https://github.com/Tendrl/api/blob/11fdde91b6618a59110fd1c43d46243f4c07a075/Rakefile#L12).

@pmjunior You can change password [via API](https://github.com/Tendrl/api/blob/master/docs/users.adoc#update-user). You just have to specify also email for `admin` user because it won't let you update user without email.
