### ISSUE TITLE
cluster list API  should list all the clusters which are already imported and ready to import

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#234]

**Comment by r0h4n** [comment]
Is this done @anivargi @gnehapk ?

**Comment by anivargi** [comment]
@r0h4n No, we need to discuss this, and understand the new etcd attributes for cluster

**Comment by mbukatov** [comment]
Here is a quick unsolicited update on this, but I hope it will be useful.  Bear in mind that it's is based on playing with `tendrl-api-1.5.0-1.el7.centos.noarch`.

I have noticed that reply of `GetNodeList` API call contains some list of clusters already (among lot of other things actually ...):

```
$ curl -XGET -H "Authorization: Bearer $ACCESS_TOKEN" http://${TENDRL_SERVER}/api/1.0/GetNodeList | jq '.clusters'
[
  {
    "cluster_id": "9ddc7fbc08525435df87f236b11d0466cca2de6d1d72d5eec84ae6fbda860e63",
    "sds_name": "gluster",
    "sds_version": "3.10.3",
    "node_ids": [
      "905c8d0a-1abc-4386-b5ff-ba8d27906333",
      "228717c4-4ea8-4792-9c4d-0b0ee392854a",
      "9887f530-fe1f-484a-b69e-0fa25872da11",
      "2c6d9b76-e8e6-4bbc-ab16-57c0692b8de3"
    ]
  }
]
```

So in this case, I see a cluster ready to be imported (but the question is if this information belongs into the reply of `GetNodeList` call).

Which is interesting, because to create import cluster request, I need to resend the list of node ids and storage type (which is called `sds_name` in GetNodeList` reply and `sds_type` in ImportCluster` request) again. Here is an example of doing this in python via request library:

```
auth = login("admin", "adminuser")
request = requests.get(USM_API_URL + "GetNodeList", auth=auth)
getnodelist_data = request.json()
for cluster in getnodelist_data["clusters"]:
    print("cluster_id:", cluster['cluster_id'])
    import_data = {
        "node_ids": cluster["node_ids"],
        "sds_type": cluster["sds_name"],
        }
    import_request = requests.post( 
        USM_API_URL + "ImportCluster",
        json=import_data,
        auth=auth)
    print("import", import_request)
```

I guess that this is going to be aligned during the work on this issue ...  which brings me to a question: how we are going to do this? Do we plan to allow import using just the cluster id?

But let's go back to the cluster list. When I retry the first query again, I don't see any clusters anymore:

```
$ curl -XGET -H "Authorization: Bearer $ACCESS_TOKEN" http://${TENDRL_SERVER}/api/1.0/GetNodeList | jq '.clusters'
[]
```

Which suggests that the meaning of this value is *clusters ready to be imported*.

**Comment by anivargi** [comment]
@mbukatov please refer updated API doc https://github.com/Tendrl/api/blob/master/docs/clusters.adoc#import-cluster

The managed and imported status can be checked using `is_managed` and `import_status` in clusters list view.
