### ISSUE TITLE
Unify etcd.yml location

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#29]
When you install tendrl-api from source than etcd.yml is located in <tendrl-api-dir>/config/etcd.yml. When you install tendrl-api from packages than etcd.yml is located in /etc/tendrl/etcd.yml. This sould be unified for both types of installation (it should be in /etc/tendrl/etcd.yml for installation from sources too).

**Comment by TimothyAsir** [comment]
Actually we used two different ways to keep the file etcd.yml is to support rpm installation and bundler installation. Using bundler installation we can have any number of instance with different versions of ruby gems which may have different versions of etcd.yml from a specific directory. So that we thought of keeping it in config folder. Where as for rpm installation we (can) provide unique path to keep the file under /etc/tendrl/etcd.yml.

However, by considering unification, we can first check in /etc/tendrl/etcd.yml if no config is found and if its a bundler based installation we can search the configuration from config directory.

**Comment by TimothyAsir** [comment]
We are currently loading etcd.yml if its available in /etc/tendrl otherwise we are loading it from config folder only.

Does this resolve this issue and can we close this as resolved?

**Comment by sankarshanmukhopadhyay** [comment]
@TimothyAsir - can we have some additional detail.

- when using an RPM based installation - where is the configuration file located and read from

- when using a bundler approach - where is the configuration file located and read from

**Comment by mbukatov** [comment]
Does it mean that I can put configuration files for tednrl-api into `/etc/tendrl/` no matter which way is the api installed?

**Comment by mbukatov** [comment]
Since there is no response, I would like to make clear how QE team is going to approach this during integration testing: all configuration files, including ones related to `tednrl-api` are going to be installed to `/tec/tendrl/` directory. This applies for both installation from source and rpm packages. So far, this seems to work. If this doesn't work, it's obviously a blocker bug (as it would prevent tendrl to be configured properly).

**Comment by sankarshanmukhopadhyay** [comment]
@TimothyAsir @brainfunked - please update accordingly

**Comment by mbukatov** [comment]
I guess this can be closed (we no longer need to install directly from sources thanks to copr build system).

**Comment by fbalak** [comment]
@mbukatov I agree --> closing
