### ISSUE TITLE
Bricks count in '/api/1.0/clusters/{cluster_id}/nodes' API.

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#342]

**Comment by shtripat** [comment]
@gnehapk we have brick count at volume level and not nodes level at the moment. But there is no count maintained at nodes level. We need backend as well as API changes to include this count.

**Comment by shtripat** [comment]
@gnehapk so `/clusters/{int}/Bricks/all/{node-fqdn}` contains brick details so count(`/clusters/{int}/Bricks/all/{node-fqdn}`) would actuall give the node wise count for the bricks. So ideally API layer can perform this and return the value. Attaching a field at Node object level is not correct because node is a common object and gluster specific fields should not be added there.

**Comment by r0h4n** [comment]
@gnehapk Do you need per node brick count or the total brick count for the entire cluster?

**Comment by gnehapk** [comment]
@r0h4n Per node brick count.

**Comment by gnehapk** [comment]
Brick count in now present in the API response of `/api/1.0/clusters/{cluster_id}/nodes`. Hence, closing this issue.
