### ISSUE TITLE
Inconsistent boolean values among different API calls

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#372]
Boolean values are inconsistent among API calls. Boolean attributes in response JSON of [clusters API call](https://github.com/Tendrl/api/blob/master/docs/clusters.adoc) have values `"yes"` and `"no"` but boolean attributes in response JSON of [users API call](https://github.com/Tendrl/api/blob/master/docs/users.adoc) have values `true` and `false`. All boolean attributes in all API calls should use values `true` and `false`.

Tested with:
```
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
```

**Comment by shirshendu** [comment]
In the clusters API calls, as far as I can find, there were only two scenarios for 'yes': volume profiling, and the `is_managed` datapoint.

Since volume profiling is now done via an `enable/disable` flag, yes/no is invalid for that scenario.
The `is_managed` datapoint cannot be fixed in tendrl-api, as setting its value is a part of the node-agent, and gluster-integration; and it also appears a bunch of times in commons:
https://github.com/Tendrl/node-agent/search?utf8=%E2%9C%93&q=is_managed&type=
https://github.com/Tendrl/gluster-integration/search?utf8=%E2%9C%93&q=is_managed&type=
https://github.com/Tendrl/commons/search?p=1&q=is_managed&type=&utf8=%E2%9C%93

And of course, UI will need to reflect the change as well.
https://github.com/Tendrl/ui/search?utf8=%E2%9C%93&q=is_managed&type=

@r0h4n Is it fine to file an issue linking back to this in each repo, and close this?

**Comment by shtripat** [comment]
I remember this was discussed last week is some daily call that etcd doesnt have boolean types and we are using string for the same. There is plan to change all such values as yes/no only backend. @r0h4n comments?

**Comment by r0h4n** [comment]
Please close this API issue. We are using yes/no consistently at the backend now. API simply fetches these attributes
