### ISSUE TITLE
Imported cluster is not in a list of clusters when import job is finished

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#67]
I call `ImportCluster` api call for importing gluster cluster, wait for status of import job to be "finished" and then I get list of clusters via `GetClusterList` api call. If I call `GetClusterList` right after job is finished the imported cluster is not in the returned response. I have to wait for a second.
If status of import job is finished then the imported cluster should already be in a list of clusters.
Tested with tendrl-api-1.2-02_01_2017_01_51_04.noarch.

**Comment by anivargi** [comment]
@nthomas-redhat is this a known issue, where after the job it takes sometime for it to reflect in etcd?

**Comment by fbalak** [comment]
I tried to reproduce this issue and it seems that the problem occurs when there are imported more than 11 clusters. Otherwise it works fine.

**Comment by nthomas-redhat** [comment]
@fbalak , I am not going to worry about this because you see the cluster in etcd after a 'second'. The import API doesn't add the cluster into etcd rather it installs the required packages, generate the config files and then starts up the integration process. The integration process then pushes the details to etcd. So you might be seeing this one second delay just because of slow network connection or something related to that.
Please close this issue if this makes sense to you

**Comment by mkudlej** [comment]
@nthomas-redhat I think that this bug is valid. Until cluster is not in GetClusterList output, import job should be marked as not finished. I think this is important for API usability. I expect that every integration with another project via API will be like this:
1) run import cluster API function
2) wait for import cluster job finish
3) do anything with imported cluster including list of clusters(for example for getting cluster ID)
If 2) is done and cluster is not in output of 3) then it is in inconsistent state and should be fixed.

**Comment by nthomas-redhat** [comment]
@nnDarshan , Can you have a look at this.
Myself and @r0h4n had a discussion;  in the generic import flow wait till the data is imported before marking the job status as 'done'.

**Comment by nnDarshan** [comment]
@nthomas-redhat Have sent a fix to node agent: https://github.com/Tendrl/node-agent/pull/210

**Comment by r0h4n** [comment]
@fbalak could you please verify if this is still a valid bug? You can use the latest copr builds

**Comment by r0h4n** [comment]
@fbalak Please verify this one, closing for now

**Comment by fbalak** [comment]
Seems ok.

Tested with:
tendrl-api-1.2-02_28_2017_01_51_02.noarch
tendrl-commons-1.2-02_28_2017_04_42_02.noarch
tendrl-node-agent-1.2-02_28_2017_00_01_02.noarch
tendrl-performance-monitoring-1.2-02_28_2017_13_18_20.noarch
tendrl-gluster-integration-1.2-02_28_2017_14_48_15.noarch
